Feature/recipe instructions
CS2103-AY1819S1-W10-4/main pull request #136
Opened 2018-10-24 13:14 UTC by junrong09

2018-10-24 13:15 UTC, junrong09 commented
Closes #97, closes #14

2018-10-24 13:21 UTC, barkhyehyeon commented on src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
> +    }
This getter name is duplicated with getAmount method of other Ingredient related classes. Please remove this part.

2018-10-24 13:23 UTC, barkhyehyeon requested changes

2018-10-24 13:23 UTC, barkhyehyeon commented on src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
> +    }
This getter name is duplicated with getAmount method of other Ingredient related classes. Please remove this part.

2018-10-24 13:23 UTC, barkhyehyeon commented on src/main/java/seedu/souschef/model/recipe/Recipe.java
> +        }
Also this will be slightly changed according to the changes in IngredientDefinition class etc. Please remove this part too.

2018-10-26 07:29 UTC, barkhyehyeon submitted a review, later dismissed

2018-10-26 08:07 UTC, BennTay commented on src/main/java/seedu/souschef/ui/MainWindow.java
> +    /*void releaseResources() {
Dead code can be deleted.

2018-10-26 08:12 UTC, BennTay commented on src/main/java/seedu/souschef/ui/UiManager.java
> +        //mainWindow.releaseResources();
Dead code can be deleted.

2018-10-26 08:50 UTC, junrong09 commented on src/main/java/seedu/souschef/ui/UiManager.java
> +        //mainWindow.releaseResources();
Dead code removed

2018-10-26 08:51 UTC, junrong09 commented on src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
> +    }
Method name refactored.

2018-10-26 08:51 UTC, BennTay approved these changes
Recipe instruction implementation approved.

2018-10-26 08:51 UTC, merged