HealthPlan show Meal Plan enhancement
CS2103-AY1819S1-W10-4/main pull request #139
Opened 2018-10-25 14:07 UTC by AlecNgZW

some minor UI implementation to hide and show the mealPlan list on the browser panel

2018-10-28 08:35 UTC, junrong09 requested changes
Capitalise all the first word of ur command success messages.
Create separate classes for parsing ur command, try not to do it within ur command class itself.
Other minor reviews are as stated in the individual review comments.

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/ShowHealthPlanDetailsCommand.java
> +    public ShowHealthPlanDetailsCommand(Ui ui, String index) {
Please make us of event center to subscribe to change in event.

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/AddMealHealthPlanCommand.java
> +    public static final String MESSAGE_SUCCESS = "added day %2$s to plan %1$s";
Capitalise the first word of the message.

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/AddMealHealthPlanCommand.java
> +        argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_PLAN, PREFIX_DURATION);
Do perform parsing in ur AddMealHealthPlanCommandParser.

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/DeleteMealHealthPlanCommand.java
> +    public static final String MESSAGE_SUCCESS = "removed day %2$s from plan %1$s";
Capitalise the first word

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/DeleteMealHealthPlanCommand.java
> +        argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_PLAN, PREFIX_DURATION);
Please perform parsing in ur command parser.

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/DisplayMealPlanCommand.java
> +    public static final String MESSAGE_SUCCESS_HIDE = "hide meal plans.";
Capitalisation

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/commands/ShowHealthPlanDetailsCommand.java
> +    public static final String MESSAGE_SUCCESS = "showing details of plan %1$s.";
Capitalisation

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/parser/AppContentParser.java
> +                    userInput, ui);
With event, do you still need UI as parameter?

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/parser/contextparser/HealthPlanParser.java
> +                                            String userInput, Ui ui) throws ParseException {
Can UI be removed as parameters?

2018-10-28 08:35 UTC, junrong09 commented on src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
> +            EventsCenter.getInstance().post(new BrowserUiChangedEvent("hide"));
Perform the posting of hide event in the ui.switchToXXXListPanel() method. Same for other context switch.

2018-10-28 08:40 UTC, BennTay commented on src/main/java/seedu/souschef/logic/parser/ParserUtil.java
> +
Please remove excess newlines

2018-10-30 09:17 UTC, barkhyehyeon submitted a review, later dismissed
Good implementation as always. Approve PR.

2018-10-30 09:17 UTC, barkhyehyeon commented on src/main/java/seedu/souschef/logic/commands/AddMealHealthPlanCommand.java
> +public class AddMealHealthPlanCommand <T extends UniqueType> extends Command {
I guess this command doesn't have to be generic, but just leaving it as it is would also be fine!

2018-10-30 09:48 UTC, junrong09 approved these changes
Approve PR. Comprehensive enhancement of health plan feature.

2018-10-30 09:48 UTC, merged